/* ---------- data ---------- */
const CATS={bas:"Basis & begroeting",tijd:"Getallen & tijd",eten:"Eten & drinken",fam:"Familie & mensen",verb:"Alledaagse werkwoorden",reis:"Onderweg & reizen",rest:"In het restaurant",hotel:"In het hotel",zwit:"Bergen & wandelen",ch:"Typisch Zwitsers (CH)",sport:"Sport & lichaam",auto:"Auto & detailing",werk:"Werk & geld",spreek:"Gesprek & mening",zin:"Nuttige zinnetjes",gram:"Grammatica-drills"};
const CAT_ICON={bas:"👋",tijd:"⏰",eten:"🍽️",fam:"👪",verb:"🏃",reis:"✈️",rest:"🍜",hotel:"🏨",zwit:"⛰️",ch:"🇨🇭",sport:"🏋️",auto:"🚗",werk:"💼",spreek:"💬",zin:"🗣️",gram:"📐"};
const LVL_LABEL={A1:"Makkelijk",A2:"Gemiddeld",B1:"Moeilijk",Alles:"Alles"};
const MODE_LABEL={mixed:"Sessie",new:"Nieuwe woorden",review:"Herhalen",check:"Controleren"};

/* Woorden staan per categorie in een eigen array: [niveau, artikel(r/e/s/-), Duits, Nederlands].
   Nieuwe woorden hoort je hier steeds AAN HET EIND van het juiste blok toe te voegen
   (nooit ertussenin), zodat je voortgang per woord stabiel blijft. */
const WORDS_BAS=[
["A1","-","Guten Morgen","goedemorgen"],["A1","-","Guten Tag","goedendag"],["A1","-","Guten Abend","goedenavond"],["A1","-","Tschüss","doei"],["A1","-","Auf Wiedersehen","tot ziens"],["A1","-","bitte","alsjeblieft / graag gedaan"],["A1","-","danke","dank je"],["A1","-","Entschuldigung","sorry / pardon"],["A1","-","Wie geht's?","hoe gaat het?"],["A1","-","gut","goed"],["A1","-","schlecht","slecht"],["A1","-","Ich heiße …","ik heet …"],["A1","-","Ich komme aus den Niederlanden","ik kom uit Nederland"],["A1","-","Ich verstehe nicht","ik begrijp het niet"],["A1","-","langsam","langzaam"],["A1","-","natürlich","natuurlijk"],["A1","-","genau","precies / klopt"],["A1","-","leider","helaas"],["A1","-","gerne","graag"],["A1","-","vielleicht","misschien"],["A1","-","Hallo","hallo"],["A1","-","Ja","ja"],["A1","-","Nein","nee"],["A2","-","Wie bitte?","pardon? (niet verstaan)"],["A2","-","Viel Glück","veel geluk"],["B1","-","Es freut mich","aangenaam kennis te maken"],["B1","-","Macht nichts","het geeft niet"]
];
const WORDS_TIJD=[
["A1","-","eins","één"],["A1","-","zwei","twee"],["A1","-","drei","drie"],["A1","-","vier","vier"],["A1","-","fünf","vijf"],["A1","-","sechs","zes"],["A1","-","sieben","zeven"],["A1","-","acht","acht"],["A1","-","neun","negen"],["A1","-","zehn","tien"],["A1","-","zwanzig","twintig"],["A1","-","hundert","honderd"],["A1","-","heute","vandaag"],["A1","-","morgen","morgen"],["A1","-","gestern","gisteren"],["A1","-","jetzt","nu"],["A1","-","später","later"],["A1","e","Stunde","uur (60 min)"],["A1","e","Woche","week"],["A1","s","Jahr","jaar"],["A1","-","elf","elf"],["A1","-","zwölf","twaalf"],["A1","-","dreißig","dertig"],["A1","-","Montag","maandag"],["A1","-","Freitag","vrijdag"],["A2","r","Monat","maand"],["A2","-","immer","altijd"],["A2","-","manchmal","soms"],["B1","-","demnächst","binnenkort"]
];
const WORDS_ETEN=[
["A1","s","Wasser","water"],["A1","r","Kaffee","koffie"],["A1","r","Tee","thee"],["A1","s","Brot","brood"],["A1","r","Käse","kaas"],["A2","s","Frühstück","ontbijt"],["A2","s","Mittagessen","lunch"],["A2","s","Abendessen","avondeten"],["A1","r","Apfel","appel"],["A1","s","Fleisch","vlees"],["A2","s","Hähnchen","kip (gerecht)"],["A1","r","Fisch","vis"],["A2","s","Gemüse","groente"],["A2","s","Obst","fruit"],["A2","e","Rechnung","rekening"],["A2","-","bestellen","bestellen"],["A1","-","lecker","lekker"],["A2","-","satt","vol (verzadigd)"],["A1","s","Restaurant","restaurant"],["A2","e","Speisekarte","menukaart"],["A2","s","Bier","bier"],["A2","r","Wein","wijn"],["A2","e","Suppe","soep"],["A2","r","Salat","salade"],["A2","e","Milch","melk"],["A2","s","Ei","ei"],["B1","-","würzig","pittig / kruidig"],["B1","-","vegetarisch","vegetarisch"]
];
const WORDS_FAM=[
["A1","e","Familie","familie / gezin"],["A1","r","Vater","vader"],["A1","e","Mutter","moeder"],["A1","r","Bruder","broer"],["A1","e","Schwester","zus"],["A1","r","Sohn","zoon"],["A1","e","Tochter","dochter"],["A1","r","Freund","vriend"],["A1","e","Freundin","vriendin"],["A1","r","Mann","man"],["A1","e","Frau","vrouw"],["A1","s","Kind","kind"],["A1","e","Eltern","ouders"],["A1","r","Opa","opa"],["A1","e","Oma","oma"],["A2","-","verheiratet","getrouwd"],["A2","r","Nachbar","buurman"],["A1","e","Leute","mensen"],["A1","-","jung","jong"],["A1","-","alt","oud"],["A2","r","Onkel","oom"],["A2","e","Tante","tante"],["B1","-","geschieden","gescheiden"],["B1","r","Enkel","kleinzoon"],["B1","-","verwandt","verwant"]
];
const WORDS_VERB=[
["A1","-","sein","zijn"],["A1","-","haben","hebben"],["A1","-","gehen","gaan / lopen"],["A1","-","kommen","komen"],["A1","-","machen","doen / maken"],["A1","-","sagen","zeggen"],["A1","-","sehen","zien"],["A1","-","hören","horen"],["A1","-","sprechen","spreken"],["A1","-","essen","eten"],["A1","-","trinken","drinken"],["A1","-","kaufen","kopen"],["A1","-","brauchen","nodig hebben"],["A1","-","wissen","weten"],["A2","-","denken","denken"],["A2","-","finden","vinden"],["A2","-","helfen","helpen"],["A2","-","suchen","zoeken"],["A1","-","geben","geven"],["A1","-","nehmen","nemen"],["A2","-","arbeiten","werken"],["A2","-","spielen","spelen"],["A2","-","lesen","lezen"],["A2","-","schreiben","schrijven"],["B1","-","erlauben","toestaan"],["B1","-","vermeiden","vermijden"],["B1","-","sich beeilen","zich haasten"]
];
const WORDS_REIS=[
["A2","r","Bahnhof","station"],["A2","r","Zug","trein"],["A2","s","Flugzeug","vliegtuig"],["A2","r","Flughafen","luchthaven"],["A2","e","Fahrkarte","kaartje / ticket"],["A1","-","links","links"],["A1","-","rechts","rechts"],["A2","-","geradeaus","rechtdoor"],["A1","e","Straße","straat"],["A1","e","Stadt","stad"],["A1","s","Hotel","hotel"],["A1","s","Zimmer","kamer"],["A2","r","Schlüssel","sleutel"],["A2","e","Reise","reis"],["A2","r","Urlaub","vakantie"],["A2","s","Gepäck","bagage"],["A2","-","abfahren","vertrekken"],["A2","-","ankommen","aankomen"],["A2","-","buchen","boeken"],["B1","r","Ausflug","uitje / excursie"],["A2","r","Koffer","koffer"],["A2","e","Verspätung","vertraging"],["A2","r","Ausweis","identiteitsbewijs"],["B1","r","Anschluss","aansluiting (overstap)"],["B1","-","umsteigen","overstappen"],["B1","e","Grenze","grens"]
];
const WORDS_SPORT=[
["A2","r","Sport","sport"],["A2","-","trainieren","trainen"],["A1","-","laufen","hardlopen / lopen"],["A2","-","schwimmen","zwemmen"],["B1","r","Muskel","spier"],["A2","-","stark","sterk"],["A1","-","müde","moe"],["A2","-","gesund","gezond"],["A1","-","krank","ziek"],["A2","r","Körper","lichaam"],["A2","s","Herz","hart"],["B1","-","atmen","ademen"],["B1","-","sich ausruhen","uitrusten"],["A2","r","Schlaf","slaap"],["A1","-","schlafen","slapen"],["A2","s","Ziel","doel"],["A1","-","schnell","snel"],["B1","e","Kraft","kracht"],["A2","-","üben","oefenen"],["B1","s","Gewicht","gewicht"],["A2","-","spazieren","wandelen (rustig)"],["A2","-","fit","fit"],["B1","-","sich verletzen","zich blesseren"],["B1","e","Verletzung","blessure"],["B1","-","sich erholen","herstellen"]
];
const WORDS_AUTO=[
["A1","s","Auto","auto"],["A2","r","Wagen","wagen / auto"],["A2","r","Reifen","band"],["A2","s","Rad","wiel"],["A2","r","Motor","motor"],["B1","e","Motorhaube","motorkap"],["A2","r","Kofferraum","kofferbak"],["B1","e","Windschutzscheibe","voorruit"],["B1","r","Lack","lak"],["B1","e","Felge","velg"],["A2","s","Leder","leer"],["B1","r","Kratzer","kras"],["B1","-","polieren","polijsten"],["A2","-","reinigen","reinigen"],["A1","-","waschen","wassen"],["B1","r","Schaum","schuim"],["B1","s","Tuch","doek"],["B1","r","Staubsauger","stofzuiger"],["B1","-","glänzen","glanzen"],["A2","e","Werkstatt","werkplaats / garage"],["A2","-","tanken","tanken"],["A2","e","Bremse","rem"],["B1","r","Sicherheitsgurt","veiligheidsgordel"],["B1","-","reparieren","repareren"],["B1","r","Ölwechsel","olieverversing"]
];
const WORDS_WERK=[
["A1","e","Arbeit","werk"],["A2","r","Kunde","klant"],["A2","r","Termin","afspraak"],["A2","e","Firma","bedrijf"],["A2","r","Preis","prijs"],["A1","s","Geld","geld"],["A1","-","teuer","duur"],["A2","-","günstig","voordelig"],["B1","r","Vertrag","contract"],["B1","e","Versicherung","verzekering"],["B1","e","Steuer","belasting"],["B1","-","selbstständig","zelfstandig (zzp)"],["B1","s","Angebot","offerte / aanbod"],["A2","-","verdienen","verdienen"],["A2","-","bezahlen","betalen"],["A2","-","pünktlich","stipt / op tijd"],["B1","r","Feierabend","einde van de werkdag"],["B1","e","Erfahrung","ervaring"],["B1","-","zuverlässig","betrouwbaar"],["A2","r","Chef","baas"],["A2","r","Kollege","collega (man)"],["A2","e","Kollegin","collega (vrouw)"],["B1","e","Kündigung","ontslag"],["B1","-","verhandeln","onderhandelen"],["A2","-","Ich habe morgen frei.","ik heb morgen vrij"],["B1","e","Gehaltserhöhung","loonsverhoging"],["A2","r","Lohn","loon"],["B1","-","Ich arbeite von zu Hause aus.","ik werk vanuit huis"]
];
const WORDS_SPREEK=[
["B1","e","Meinung","mening"],["B1","-","Ich finde, dass …","ik vind dat …"],["B1","-","einverstanden","akkoord / mee eens"],["B1","r","Vorschlag","voorstel"],["A2","e","Frage","vraag"],["A2","e","Antwort","antwoord"],["B1","-","erklären","uitleggen"],["A2","-","verstehen","begrijpen"],["B1","-","empfehlen","aanbevelen"],["B1","-","eigentlich","eigenlijk"],["B1","-","wahrscheinlich","waarschijnlijk"],["A2","-","wichtig","belangrijk"],["B1","e","Entscheidung","beslissing"],["B1","-","entscheiden","beslissen"],["B1","-","sich freuen auf","zich verheugen op"],["A2","-","Es tut mir leid","het spijt me"],["A1","-","kein Problem","geen probleem"],["B1","r","Grund","reden"],["B1","-","deshalb","daarom"],["B1","-","zwar … aber","weliswaar … maar"],["A2","-","stimmen","kloppen (juist zijn)"],["B1","-","zustimmen","instemmen"],["B1","-","bezweifeln","betwijfelen"],["B1","e","Ausrede","excuus"],["B1","-","übertreiben","overdrijven"]
];
const WORDS_REST=[
["A2","-","Einen Tisch für zwei, bitte.","een tafel voor twee, graag"],["A2","-","Die Speisekarte, bitte.","de menukaart, graag"],["A2","-","Ich hätte gern ein Wasser.","ik wil graag een water"],["A2","-","Was können Sie empfehlen?","wat kunt u aanbevelen?"],["A2","-","Ich nehme das Schnitzel.","ik neem de schnitzel"],["A2","-","Die Rechnung, bitte.","de rekening, graag"],["A2","-","Zusammen oder getrennt?","samen of apart (betalen)?"],["B1","-","Stimmt so.","laat maar zitten (fooi)"],["A2","-","Kann ich mit Karte zahlen?","kan ik pinnen?"],["A2","-","Es hat sehr gut geschmeckt.","het heeft erg goed gesmaakt"],["A1","-","Guten Appetit!","eet smakelijk"],["A2","-","Noch etwas?","nog iets?"],["B1","-","Ich bin allergisch gegen Nüsse.","ik ben allergisch voor noten"],["A2","-","Ohne Zwiebeln, bitte.","zonder ui, graag"],["A2","s","Leitungswasser","kraanwater"],["A2","-","Ich habe eine Reservierung.","ik heb een reservering"],["A2","-","Für wie viele Personen?","voor hoeveel personen?"],["A2","-","Was empfehlen Sie?","wat beveelt u aan?"],["A2","r","Nachtisch","toetje / dessert"],["A2","e","Vorspeise","voorgerecht"],["A2","s","Hauptgericht","hoofdgerecht"],["A2","-","Ist der Tisch frei?","is deze tafel vrij?"],["A2","r","Kellner","ober"],["A2","e","Kellnerin","serveerster"],["A2","-","Zum Wohl!","proost!"],["B1","-","Ich hätte gern getrennte Rechnungen.","ik wil graag apart afrekenen"],["A2","-","Können wir noch etwas Brot haben?","kunnen we nog wat brood krijgen?"],["A2","s","Trinkgeld","fooi"],["B1","-","Ist das scharf?","is dit pittig?"],["A2","-","Ich bin satt.","ik zit vol"]
];
const WORDS_HOTEL=[
["A2","-","Ich habe ein Zimmer reserviert.","ik heb een kamer gereserveerd"],["A2","-","Auf den Namen …","op naam van …"],["A2","-","Ein Doppelzimmer für zwei Nächte.","een tweepersoonskamer voor twee nachten"],["A2","-","Ist das Frühstück inbegriffen?","is het ontbijt inbegrepen?"],["A2","-","Wann gibt es Frühstück?","hoe laat is het ontbijt?"],["A2","-","Bis wann ist der Check-out?","tot hoe laat is het uitchecken?"],["A2","-","Wie ist das WLAN-Passwort?","wat is het wifi-wachtwoord?"],["A2","-","Gibt es einen Parkplatz?","is er een parkeerplaats?"],["B1","-","Das Zimmer ist zu laut.","de kamer is te lawaaiig"],["B1","-","Die Heizung funktioniert nicht.","de verwarming doet het niet"],["B1","-","Kann ich mein Gepäck hier lassen?","kan ik mijn bagage hier laten?"],["A2","-","Können Sie ein Taxi rufen?","kunt u een taxi bellen?"],["A2","e","Rezeption","receptie"],["A2","r","Aufzug","lift"],["A2","-","Ich möchte ein Zimmer buchen.","ik wil graag een kamer boeken"],["A2","s","Einzelzimmer","eenpersoonskamer"],["A2","e","Nacht","nacht (verblijf)"],["A2","-","Haben Sie noch freie Zimmer?","heeft u nog kamers vrij?"],["A2","e","Minibar","minibar"],["A2","s","Handtuch","handdoek"],["A2","-","Können Sie mich um sieben Uhr wecken?","kunt u me om zeven uur wekken?"],["B1","-","Das WLAN funktioniert nicht.","de wifi werkt niet"],["A2","-","Ich möchte auschecken.","ik wil graag uitchecken"],["A2","r","Zimmerservice","roomservice"],["B1","-","Können Sie uns ein anderes Zimmer geben?","kunt u ons een andere kamer geven?"],["A2","-","Wo kann ich parken?","waar kan ik parkeren?"],["A2","e","Bettwäsche","beddengoed"],["A2","-","Ist das Zimmer noch frei?","is de kamer nog vrij?"]
];
const WORDS_CH=[
["A1","-","Grüezi","hallo (Zwitsers)"],["A2","-","Merci vilmal","dank je wel (Zwitsers)"],["A2","s","Velo","fiets (Zwitsers-Duits)"],["A2","s","Billett","kaartje (Zwitsers-Duits)"],["A2","r","Franken","frank (CHF)"],["A2","-","Grüezi mitenand","hallo allemaal (Zwitsers)"],["A2","-","Uf Widerluege","tot ziens (Zwitsers)"],["B1","-","parkieren","parkeren (Zwitsers, DE: parken)"],["B1","s","Trottoir","stoep (Zwitsers, DE: Gehweg)"],["B1","s","Poulet","kip (Zwitsers, DE: Hähnchen)"],["B1","s","Znüni","tussendoortje rond 9 uur (Zwitsers)"],["B1","-","Es isch guet.","het is goed (Zwitsers)"],["A2","s","Müesli","muesli (Zwitsers ontbijt)"],["B1","r","Coiffeur","kapper (Zwitsers, DE: Friseur)"],["A2","-","Zmorge","ontbijt (Zwitsers, DE: Frühstück)"],["A2","-","Zmittag","lunch (Zwitsers, DE: Mittagessen)"],["A2","-","Znacht","avondeten (Zwitsers, DE: Abendessen)"],["B1","-","Zvieri","tussendoortje in de namiddag (Zwitsers)"],["A2","s","Natel","mobiele telefoon (Zwitsers woord)"],["B1","-","Röstigraben","denkbeeldige grens tussen Duits- en Franstalig Zwitserland"],["A2","-","Postauto","(post)bus op het platteland (Zwitsers)"],["B1","-","Beiz","eenvoudig café/kroeg (Zwitsers, DE: Kneipe)"],["A2","-","Guetzli","koekje (Zwitsers, DE: Keks)"],["B1","-","Chuchichäschtli","keukenkastje (bekend Zwitsers-Duits testwoord)"],["A1","-","Salü","hoi / hallo (informeel Zwitsers)"],["A2","-","Tschau zäme","doei allemaal (Zwitsers)"]
];
const WORDS_ZWIT=[
["A1","r","Berg","berg"],["A2","s","Tal","dal"],["B1","r","Gipfel","bergtop"],["A1","r","See","meer"],["A2","e","Seilbahn","kabelbaan"],["A2","e","Wanderung","bergwandeling / hike"],["A2","-","wandern","wandelen (in de bergen)"],["B1","r","Wanderweg","wandelpad"],["B1","e","Hütte","berghut"],["A1","s","Wetter","weer"],["A1","r","Schnee","sneeuw"],["B1","e","Aussicht","uitzicht"],["B1","-","steil","steil"],["B1","-","Ist der Weg schwierig?","is de route moeilijk?"],["A2","-","Wie komme ich zum Bahnhof?","hoe kom ik bij het station?"],["A2","r","Gletscher","gletsjer"],["B1","e","Alp","alpenweide"],["A2","-","klettern","klimmen"],["B1","-","rutschig","glad (onder de voeten)"],["A2","-","bergauf","bergop"],["A2","-","bergab","bergaf"],["B1","e","Höhe","hoogte"],["A2","r","Pass","bergpas"],["B1","-","Wir haben den Gipfel erreicht.","we hebben de top bereikt"],["A2","e","Ausrüstung","uitrusting"],["A2","r","Rucksack","rugzak"],["A2","e","Wasserflasche","waterfles"],["B1","-","Der Weg ist gut markiert.","de route is goed gemarkeerd"],["A2","-","Wie lange dauert die Wanderung?","hoe lang duurt de wandeling?"],["B1","r","Nebel","mist"]
];
const WORDS_GRAM=[
["A2","-","Ich hätte gern einen Kaffee.","ik wil graag een koffie (beleefd bestellen)"],["A2","-","Ich muss morgen arbeiten.","ik moet morgen werken"],["A2","-","Ich kann dir helfen.","ik kan je helpen"],["A2","-","Ich habe gestern gearbeitet.","ik heb gisteren gewerkt"],["B1","-","Ich bin nach Hause gegangen.","ik ben naar huis gegaan"],["A2","-","Morgen gehe ich ins Fitnessstudio.","morgen ga ik naar de sportschool"],["B1","-","Ich weiß, dass es teuer ist.","ik weet dat het duur is"],["B1","-","Ich sehe den Mann.","ik zie de man"],["B1","-","Ich helfe dem Mann.","ik help de man"],["A1","-","Sprechen Sie Deutsch?","spreekt u Duits? (beleefd)"],["A1","-","Kannst du mir helfen?","kun je me helpen? (informeel)"],["B1","-","Ich freue mich auf den Urlaub.","ik verheug me op de vakantie"],["A2","-","Am Wochenende fahre ich nach Bern.","in het weekend rijd ik naar Bern"],["B1","-","Ich glaube, dass er recht hat.","ik denk dat hij gelijk heeft"],["B1","-","Ich rufe dich an, wenn ich Zeit habe.","ik bel je als ik tijd heb"],["B1","-","Der Kunde wartet auf die Antwort.","de klant wacht op het antwoord"],["B1","-","Ich gebe der Frau das Buch.","ik geef de vrouw het boek"],["A2","-","Wir sind ins Kino gegangen.","we zijn naar de bioscoop gegaan"],["A2","-","Hast du das Auto gewaschen?","heb je de auto gewassen?"],["B1","-","Ich darf heute später kommen.","ik mag vandaag later komen"],["B1","-","Wir wollen morgen wandern gehen.","we willen morgen gaan wandelen"],["A1","-","Wie heißen Sie?","hoe heet u? (beleefd)"],["B1","-","Ich weiß nicht, ob er kommt.","ik weet niet of hij komt"],["B1","-","Ich habe ihr geholfen.","ik heb haar geholpen"],["A2","-","Kannst du mir bitte helfen?","kun je me alsjeblieft helpen?"]
];
const WORDS_ZIN=[
["A1","-","Wie spät ist es?","hoe laat is het?"],["A1","-","Wo ist die Toilette?","waar is het toilet?"],["A1","-","Was kostet das?","wat kost dat?"],["A1","-","Ich brauche Hilfe.","ik heb hulp nodig"],["A1","-","Alles klar.","helemaal duidelijk / oké"],["A2","-","Können Sie das wiederholen?","kunt u dat herhalen?"],["A2","-","Ich habe eine Frage.","ik heb een vraag"],["A2","-","Wo kann ich das kaufen?","waar kan ik dat kopen?"],["A2","-","Ich bin neu hier.","ik ben hier nieuw"],["A2","-","Das macht nichts.","dat maakt niet uit"],["B1","-","Könnten Sie mir bitte helfen?","zou u mij alstublieft kunnen helpen?"],["B1","-","Das habe ich nicht verstanden.","dat heb ik niet begrepen"],["B1","-","Wie lange dauert das?","hoe lang duurt dat?"],["B1","-","Ich melde mich später bei dir.","ik neem later contact met je op"],["B1","-","Es kommt darauf an.","het hangt ervan af"],["A1","-","Guten Rutsch!","fijne jaarwisseling!"],["A1","-","Bis bald!","tot snel!"],["A2","-","Ich brauche einen Moment.","ik heb een momentje nodig"],["A2","-","Können Sie langsamer sprechen?","kunt u langzamer spreken?"],["A2","-","Wo ist der Ausgang?","waar is de uitgang?"],["A2","-","Ich habe mich verlaufen.","ik ben verdwaald"],["B1","-","Das ergibt Sinn.","dat is logisch / dat slaat ergens op"],["A2","-","Genau richtig.","precies goed"],["B1","-","Ich bin mir nicht sicher.","ik weet het niet zeker"],["A1","-","Herzlichen Glückwunsch!","gefeliciteerd!"],["A2","-","Gute Besserung!","beterschap!"],["B1","-","Machen Sie sich keine Sorgen.","maakt u zich geen zorgen"],["A1","-","Schönen Tag noch!","nog een fijne dag!"]
];
const CATEGORY_WORDS={bas:WORDS_BAS,tijd:WORDS_TIJD,eten:WORDS_ETEN,fam:WORDS_FAM,verb:WORDS_VERB,reis:WORDS_REIS,sport:WORDS_SPORT,auto:WORDS_AUTO,werk:WORDS_WERK,spreek:WORDS_SPREEK,rest:WORDS_REST,hotel:WORDS_HOTEL,ch:WORDS_CH,zwit:WORDS_ZWIT,gram:WORDS_GRAM,zin:WORDS_ZIN};
const W=Object.entries(CATEGORY_WORDS).flatMap(([cat,list])=>list.map(w=>[cat,...w]));

const ART={r:["der","a-der"],e:["die","a-die"],s:["das","a-das"]};
const GRAM=[
["Werkwoord altijd op plek 2","In een gewone zin staat het vervoegde werkwoord ALTIJD op de tweede plek — ook als de zin met iets anders begint. Begin je met 'morgen', dan komt het werkwoord meteen daarna en schuift 'ik' erachter (inversie).",["Ich gehe morgen ins Gym.|Ik ga morgen naar de gym.","Morgen gehe ich ins Gym.|Morgen ga ik naar de gym.","Am Samstag arbeite ich nicht.|Zaterdag werk ik niet."]],
["Bijzin: werkwoord naar het einde","Na woorden als dass (dat), weil (omdat) en wenn (als) gaat het werkwoord helemaal naar het einde van de bijzin. Dit is dé regel die Duits 'Duits' maakt.",["Ich weiß, dass es teuer ist.|Ik weet dat het duur is.","Ich bleibe zu Hause, weil ich müde bin.|Ik blijf thuis omdat ik moe ben."]],
["Naamvallen light: der → den → dem","Het lidwoord verandert mee met de rol in de zin. Onderwerp: der Mann. Lijdend voorwerp (accusatief): den Mann. Na o.a. helfen, mit, zu (datief): dem Mann. Die en das veranderen alleen in de datief (der/dem).",["Der Mann ist nett.|De man is aardig. (onderwerp)","Ich sehe den Mann.|Ik zie de man. (accusatief)","Ich helfe dem Mann.|Ik help de man. (datief)"]],
["Verleden tijd: het Perfekt","Spreektaal gebruikt bijna altijd het Perfekt: haben/sein + voltooid deelwoord achteraan. Sein bij beweging of verandering (gegangen, gefahren), haben bij de rest. Net als in het Nederlands, alleen strikter: het deelwoord staat écht op het einde.",["Ich habe gestern gearbeitet.|Ik heb gisteren gewerkt.","Ich bin nach Zürich gefahren.|Ik ben naar Zürich gereden."]],
["Modale werkwoorden","Müssen (moeten), können (kunnen), wollen (willen), dürfen (mogen): het modale werkwoord staat op plek 2, het hele werkwoord gaat naar het einde.",["Ich muss morgen arbeiten.|Ik moet morgen werken.","Kann ich mit Karte zahlen?|Kan ik pinnen?","Ich will Deutsch lernen.|Ik wil Duits leren."]],
["Du of Sie? (+ Zwitserse tip)","Sie (met hoofdletter) tegen onbekenden, personeel en klanten — beleefd en altijd veilig. Du tegen vrienden en in de gym. In Zwitserland werkt je standaard Duits overal; je hoort er alleen Grüezi in plaats van Guten Tag en merci in plaats van danke. Gewoon Hochdeutsch terugpraten is prima.",["Sprechen Sie Englisch?|Spreekt u Engels?","Kannst du mir helfen?|Kun je me helpen?"]]
];
const NEW_PER_SESSION=15, MASTER_IV=21;
