/* ---------- talen ---------- */
/* Elke taal: id, weergavenaam, vlag, spraak-taalcode, of er een artikel/
   geslacht-systeem is, zijn eigen categorienamen + iconen, en (optioneel)
   een grammatica-gids. Cultuur-tokens (kleuren/landmarks/aanmoedigingen)
   worden per taal aangevuld in style.css / app.js. */
const LANG_ORDER=["de","tr"];

/* ---------- gedeelde UI-labels (taal-onafhankelijk) ---------- */
const LVL_LABEL={A1:"Makkelijk",A2:"Gemiddeld",B1:"Moeilijk",Alles:"Alles"};
const MODE_LABEL={mixed:"Sessie",new:"Nieuwe woorden",review:"Herhalen",check:"Controleren"};
const NEW_PER_SESSION=15, MASTER_IV=21;

/* ================= DUITS ================= */
const CATS_DE={bas:"Basis & begroeting",tijd:"Getallen & tijd",eten:"Eten & drinken",fam:"Familie & mensen",verb:"Alledaagse werkwoorden",reis:"Onderweg & reizen",rest:"In het restaurant",hotel:"In het hotel",zwit:"Bergen & wandelen",ch:"Typisch Zwitsers (CH)",sport:"Sport & lichaam",auto:"Auto & detailing",werk:"Werk & geld",spreek:"Gesprek & mening",zin:"Nuttige zinnetjes",gram:"Grammatica-drills"};
const CAT_ICON_DE={bas:"👋",tijd:"⏰",eten:"🍽️",fam:"👪",verb:"🏃",reis:"✈️",rest:"🍜",hotel:"🏨",zwit:"⛰️",ch:"🇨🇭",sport:"🏋️",auto:"🚗",werk:"💼",spreek:"💬",zin:"🗣️",gram:"📐"};

const WORDS_BAS=[
["A1","-","Guten Morgen","goedemorgen"],["A1","-","Guten Tag","goedendag"],["A1","-","Guten Abend","goedenavond"],["A1","-","Tschüss","doei"],["A1","-","Auf Wiedersehen","tot ziens"],["A1","-","bitte","alsjeblieft / graag gedaan"],["A1","-","danke","dank je"],["A1","-","Entschuldigung","sorry / pardon"],["A1","-","Wie geht's?","hoe gaat het?"],["A1","-","gut","goed"],["A1","-","schlecht","slecht"],["A1","-","Ich heiße …","ik heet …"],["A1","-","Ich komme aus den Niederlanden","ik kom uit Nederland"],["A1","-","Ich verstehe nicht","ik begrijp het niet"],["A1","-","langsam","langzaam"],["A1","-","natürlich","natuurlijk"],["A1","-","genau","precies / klopt"],["A1","-","leider","helaas"],["A1","-","gerne","graag"],["A1","-","vielleicht","misschien"],["A1","-","Hallo","hallo"],["A1","-","Ja","ja"],["A1","-","Nein","nee"],["A2","-","Wie bitte?","pardon? (niet verstaan)"],["A2","-","Viel Glück","veel geluk"],["B1","-","Es freut mich","aangenaam kennis te maken"],["B1","-","Macht nichts","het geeft niet"]
];
const WORDS_TIJD=[
["A1","-","eins","één"],["A1","-","zwei","twee"],["A1","-","drei","drie"],["A1","-","vier","vier"],["A1","-","fünf","vijf"],["A1","-","sechs","zes"],["A1","-","sieben","zeven"],["A1","-","acht","acht"],["A1","-","neun","negen"],["A1","-","zehn","tien"],["A1","-","zwanzig","twintig"],["A1","-","hundert","honderd"],["A1","-","heute","vandaag"],["A1","-","morgen","morgen"],["A1","-","gestern","gisteren"],["A1","-","jetzt","nu"],["A1","-","später","later"],["A1","e","Stunde","uur (60 min)"],["A1","e","Woche","week"],["A1","s","Jahr","jaar"],["A1","-","elf","elf"],["A1","-","zwölf","twaalf"],["A1","-","dreißig","dertig"],["A1","-","Montag","maandag"],["A1","-","Freitag","vrijdag"],["A2","r","Monat","maand"],["A2","-","immer","altijd"],["A2","-","manchmal","soms"],["B1","-","demnächst","binnenkort"]
];
const WORDS_ETEN=[
["A1","s","Wasser","water"],["A1","r","Kaffee","koffie"],["A1","r","Tee","thee"],["A1","s","Brot","brood"],["A1","r","Käse","kaas"],["A2","s","Frühstück","ontbijt"],["A2","s","Mittagessen","lunch"],["A2","s","Abendessen","avondeten"],["A1","r","Apfel","appel"],["A1","s","Fleisch","vlees"],["A2","s","Hähnchen","kip (gerecht)"],["A1","r","Fisch","vis"],["A2","s","Gemüse","groente"],["A2","s","Obst","fruit"],["A2","e","Rechnung","rekening"],["A2","-","bestellen","bestellen"],["A1","-","lecker","lekker"],["A2","-","satt","vol (verzadigd)"],["A1","s","Restaurant","restaurant"],["A2","e","Speisekarte","menukaart"],["A2","s","Bier","bier"],["A2","r","Wein","wijn"],["A2","e","Suppe","soep"],["A2","r","Salat","salade"],["A2","e","Milch","melk"],["A2","s","Ei","ei"],["B1","-","würzig","pittig / kruidig"],["B1","-","vegetarisch","vegetarisch"]
];
const WORDS_FAM=[
["A1","e","Familie","familie / gezin"],["A1","r","Vater","vader"],["A1","e","Mutter","moeder"],["A1","r","Bruder","broer"],["A1","e","Schwester","zus"],["A1","r","Sohn","zoon"],["A1","e","Tochter","dochter"],["A1","r","Freund","vriend"],["A1","e","Freundin","vriendin"],["A1","r","Mann","man"],["A1","e","Frau","vrouw"],["A1","s","Kind","kind"],["A1","e","Eltern","ouders"],["A1","r","Opa","opa"],["A1","e","Oma","oma"],["A2","-","verheiratet","getrouwd"],["A2","r","Nachbar","buurman"],["A1","e","Leute","mensen"],["A1","-","jung","jong"],["A1","-","alt","oud"],["A2","r","Onkel","oom"],["A2","e","Tante","tante"],["B1","-","geschieden","gescheiden"],["B1","r","Enkel","kleinzoon"],["B1","-","verwandt","verwant"]
];
const WORDS_VERB=[
["A1","-","sein","zijn"],["A1","-","haben","hebben"],["A1","-","gehen","gaan / lopen"],["A1","-","kommen","komen"],["A1","-","machen","doen / maken"],["A1","-","sagen","zeggen"],["A1","-","sehen","zien"],["A1","-","hören","horen"],["A1","-","sprechen","spreken"],["A1","-","essen","eten"],["A1","-","trinken","drinken"],["A1","-","kaufen","kopen"],["A1","-","brauchen","nodig hebben"],["A1","-","wissen","weten"],["A2","-","denken","denken"],["A2","-","finden","vinden"],["A2","-","helfen","helpen"],["A2","-","suchen","zoeken"],["A1","-","geben","geven"],["A1","-","nehmen","nemen"],["A2","-","arbeiten","werken"],["A2","-","spielen","spelen"],["A2","-","lesen","lezen"],["A2","-","schreiben","schrijven"],["B1","-","erlauben","toestaan"],["B1","-","vermeiden","vermijden"],["B1","-","sich beeilen","zich haasten"]
];
const WORDS_REIS=[
["A2","r","Bahnhof","station"],["A2","r","Zug","trein"],["A2","s","Flugzeug","vliegtuig"],["A2","r","Flughafen","luchthaven"],["A2","e","Fahrkarte","kaartje / ticket"],["A1","-","links","links"],["A1","-","rechts","rechts"],["A2","-","geradeaus","rechtdoor"],["A1","e","Straße","straat"],["A1","e","Stadt","stad"],["A1","s","Hotel","hotel"],["A1","s","Zimmer","kamer"],["A2","r","Schlüssel","sleutel"],["A2","e","Reise","reis"],["A2","r","Urlaub","vakantie"],["A2","s","Gepäck","bagage"],["A2","-","abfahren","vertrekken"],["A2","-","ankommen","aankomen"],["A2","-","buchen","boeken"],["B1","r","Ausflug","uitje / excursie"],["A2","r","Koffer","koffer"],["A2","e","Verspätung","vertraging"],["A2","r","Ausweis","identiteitsbewijs"],["B1","r","Anschluss","aansluiting (overstap)"],["B1","-","umsteigen","overstappen"],["B1","e","Grenze","grens"]
];
const WORDS_SPORT=[
["A2","r","Sport","sport"],["A2","-","trainieren","trainen"],["A1","-","laufen","hardlopen / lopen"],["A2","-","schwimmen","zwemmen"],["B1","r","Muskel","spier"],["A2","-","stark","sterk"],["A1","-","müde","moe"],["A2","-","gesund","gezond"],["A1","-","krank","ziek"],["A2","r","Körper","lichaam"],["A2","s","Herz","hart"],["B1","-","atmen","ademen"],["B1","-","sich ausruhen","uitrusten"],["A2","r","Schlaf","slaap"],["A1","-","schlafen","slapen"],["A2","s","Ziel","doel"],["A1","-","schnell","snel"],["B1","e","Kraft","kracht"],["A2","-","üben","oefenen"],["B1","s","Gewicht","gewicht"],["A2","-","spazieren","wandelen (rustig)"],["A2","-","fit","fit"],["B1","-","sich verletzen","zich blesseren"],["B1","e","Verletzung","blessure"],["B1","-","sich erholen","herstellen"]
];
const WORDS_AUTO=[
["A1","s","Auto","auto"],["A2","r","Wagen","wagen / auto"],["A2","r","Reifen","band"],["A2","s","Rad","wiel"],["A2","r","Motor","motor"],["B1","e","Motorhaube","motorkap"],["A2","r","Kofferraum","kofferbak"],["B1","e","Windschutzscheibe","voorruit"],["B1","r","Lack","lak"],["B1","e","Felge","velg"],["A2","s","Leder","leer"],["B1","r","Kratzer","kras"],["B1","-","polieren","polijsten"],["A2","-","reinigen","reinigen"],["A1","-","waschen","wassen"],["B1","r","Schaum","schuim"],["B1","s","Tuch","doek"],["B1","r","Staubsauger","stofzuiger"],["B1","-","glänzen","glanzen"],["A2","e","Werkstatt","werkplaats / garage"],["A2","-","tanken","tanken"],["A2","e","Bremse","rem"],["B1","r","Sicherheitsgurt","veiligheidsgordel"],["B1","-","reparieren","repareren"],["B1","r","Ölwechsel","olieverversing"]
];
const WORDS_WERK=[
["A1","e","Arbeit","werk"],["A2","r","Kunde","klant"],["A2","r","Termin","afspraak"],["A2","e","Firma","bedrijf"],["A2","r","Preis","prijs"],["A1","s","Geld","geld"],["A1","-","teuer","duur"],["A2","-","günstig","voordelig"],["B1","r","Vertrag","contract"],["B1","e","Versicherung","verzekering"],["B1","e","Steuer","belasting"],["B1","-","selbstständig","zelfstandig (zzp)"],["B1","s","Angebot","offerte / aanbod"],["A2","-","verdienen","verdienen"],["A2","-","bezahlen","betalen"],["A2","-","pünktlich","stipt / op tijd"],["B1","r","Feierabend","einde van de werkdag"],["B1","e","Erfahrung","ervaring"],["B1","-","zuverlässig","betrouwbaar"],["A2","r","Chef","baas"],["A2","r","Kollege","collega (man)"],["A2","e","Kollegin","collega (vrouw)"],["B1","e","Kündigung","ontslag"],["B1","-","verhandeln","onderhandelen"],["A2","-","Ich habe morgen frei.","ik heb morgen vrij"],["B1","e","Gehaltserhöhung","loonsverhoging"],["A2","r","Lohn","loon"],["B1","-","Ich arbeite von zu Hause aus.","ik werk vanuit huis"]
];
const WORDS_SPREEK=[
["B1","e","Meinung","mening"],["B1","-","Ich finde, dass …","ik vind dat …"],["B1","-","einverstanden","akkoord / mee eens"],["B1","r","Vorschlag","voorstel"],["A2","e","Frage","vraag"],["A2","e","Antwort","antwoord"],["B1","-","erklären","uitleggen"],["A2","-","verstehen","begrijpen"],["B1","-","empfehlen","aanbevelen"],["B1","-","eigentlich","eigenlijk"],["B1","-","wahrscheinlich","waarschijnlijk"],["A2","-","wichtig","belangrijk"],["B1","e","Entscheidung","beslissing"],["B1","-","entscheiden","beslissen"],["B1","-","sich freuen auf","zich verheugen op"],["A2","-","Es tut mir leid","het spijt me"],["A1","-","kein Problem","geen probleem"],["B1","r","Grund","reden"],["B1","-","deshalb","daarom"],["B1","-","zwar … aber","weliswaar … maar"],["A2","-","stimmen","kloppen (juist zijn)"],["B1","-","zustimmen","instemmen"],["B1","-","bezweifeln","betwijfelen"],["B1","e","Ausrede","excuus"],["B1","-","übertreiben","overdrijven"]
];
const WORDS_REST=[
["A2","-","Einen Tisch für zwei, bitte.","een tafel voor twee, graag"],["A2","-","Die Speisekarte, bitte.","de menukaart, graag"],["A2","-","Ich hätte gern ein Wasser.","ik wil graag een water"],["A2","-","Was können Sie empfehlen?","wat kunt u aanbevelen?"],["A2","-","Ich nehme das Schnitzel.","ik neem de schnitzel"],["A2","-","Die Rechnung, bitte.","de rekening, graag"],["A2","-","Zusammen oder getrennt?","samen of apart (betalen)?"],["B1","-","Stimmt so.","laat maar zitten (fooi)"],["A2","-","Kann ich mit Karte zahlen?","kan ik pinnen?"],["A2","-","Es hat sehr gut geschmeckt.","het heeft erg goed gesmaakt"],["A1","-","Guten Appetit!","eet smakelijk"],["A2","-","Noch etwas?","nog iets?"],["B1","-","Ich bin allergisch gegen Nüsse.","ik ben allergisch voor noten"],["A2","-","Ohne Zwiebeln, bitte.","zonder ui, graag"],["A2","s","Leitungswasser","kraanwater"],["A2","-","Ich habe eine Reservierung.","ik heb een reservering"],["A2","-","Für wie viele Personen?","voor hoeveel personen?"],["A2","-","Was empfehlen Sie?","wat beveelt u aan?"],["A2","r","Nachtisch","toetje / dessert"],["A2","e","Vorspeise","voorgerecht"],["A2","s","Hauptgericht","hoofdgerecht"],["A2","-","Ist der Tisch frei?","is deze tafel vrij?"],["A2","r","Kellner","ober"],["A2","e","Kellnerin","serveerster"],["A2","-","Zum Wohl!","proost!"],["B1","-","Ich hätte gern getrennte Rechnungen.","ik wil graag apart afrekenen"],["A2","-","Können wir noch etwas Brot haben?","kunnen we nog wat brood krijgen?"],["A2","s","Trinkgeld","fooi"],["B1","-","Ist das scharf?","is dit pittig?"],["A2","-","Ich bin satt.","ik zit vol"]
];
const WORDS_HOTEL=[
["A2","-","Ich habe ein Zimmer reserviert.","ik heb een kamer gereserveerd"],["A2","-","Auf den Namen …","op naam van …"],["A2","-","Ein Doppelzimmer für zwei Nächte.","een tweepersoonskamer voor twee nachten"],["A2","-","Ist das Frühstück inbegriffen?","is het ontbijt inbegrepen?"],["A2","-","Wann gibt es Frühstück?","hoe laat is het ontbijt?"],["A2","-","Bis wann ist der Check-out?","tot hoe laat is het uitchecken?"],["A2","-","Wie ist das WLAN-Passwort?","wat is het wifi-wachtwoord?"],["A2","-","Gibt es einen Parkplatz?","is er een parkeerplaats?"],["B1","-","Das Zimmer ist zu laut.","de kamer is te lawaaiig"],["B1","-","Die Heizung funktioniert nicht.","de verwarming doet het niet"],["B1","-","Kann ich mein Gepäck hier lassen?","kan ik mijn bagage hier laten?"],["A2","-","Können Sie ein Taxi rufen?","kunt u een taxi bellen?"],["A2","e","Rezeption","receptie"],["A2","r","Aufzug","lift"],["A2","-","Ich möchte ein Zimmer buchen.","ik wil graag een kamer boeken"],["A2","s","Einzelzimmer","eenpersoonskamer"],["A2","e","Nacht","nacht (verblijf)"],["A2","-","Haben Sie noch freie Zimmer?","heeft u nog kamers vrij?"],["A2","e","Minibar","minibar"],["A2","s","Handtuch","handdoek"],["A2","-","Können Sie mich um sieben Uhr wecken?","kunt u me om zeven uur wekken?"],["B1","-","Das WLAN funktioniert nicht.","de wifi werkt niet"],["A2","-","Ich möchte auschecken.","ik wil graag uitchecken"],["A2","r","Zimmerservice","roomservice"],["B1","-","Können Sie uns ein anderes Zimmer geben?","kunt u ons een andere kamer geven?"],["A2","-","Wo kann ich parken?","waar kan ik parkeren?"],["A2","e","Bettwäsche","beddengoed"],["A2","-","Ist das Zimmer noch frei?","is de kamer nog vrij?"]
];
const WORDS_CH=[
["A1","-","Grüezi","hallo (Zwitsers)"],["A2","-","Merci vilmal","dank je wel (Zwitsers)"],["A2","s","Velo","fiets (Zwitsers-Duits)"],["A2","s","Billett","kaartje (Zwitsers-Duits)"],["A2","r","Franken","frank (CHF)"],["A2","-","Grüezi mitenand","hallo allemaal (Zwitsers)"],["A2","-","Uf Widerluege","tot ziens (Zwitsers)"],["B1","-","parkieren","parkeren (Zwitsers, DE: parken)"],["B1","s","Trottoir","stoep (Zwitsers, DE: Gehweg)"],["B1","s","Poulet","kip (Zwitsers, DE: Hähnchen)"],["B1","s","Znüni","tussendoortje rond 9 uur (Zwitsers)"],["B1","-","Es isch guet.","het is goed (Zwitsers)"],["A2","s","Müesli","muesli (Zwitsers ontbijt)"],["B1","r","Coiffeur","kapper (Zwitsers, DE: Friseur)"],["A2","-","Zmorge","ontbijt (Zwitsers, DE: Frühstück)"],["A2","-","Zmittag","lunch (Zwitsers, DE: Mittagessen)"],["A2","-","Znacht","avondeten (Zwitsers, DE: Abendessen)"],["B1","-","Zvieri","tussendoortje in de namiddag (Zwitsers)"],["A2","s","Natel","mobiele telefoon (Zwitsers woord)"],["B1","-","Röstigraben","denkbeeldige grens tussen Duits- en Franstalig Zwitserland"],["A2","-","Postauto","(post)bus op het platteland (Zwitsers)"],["B1","-","Beiz","eenvoudig café/kroeg (Zwitsers, DE: Kneipe)"],["A2","-","Guetzli","koekje (Zwitsers, DE: Keks)"],["B1","-","Chuchichäschtli","keukenkastje (bekend Zwitsers-Duits testwoord)"],["A1","-","Salü","hoi / hallo (informeel Zwitsers)"],["A2","-","Tschau zäme","doei allemaal (Zwitsers)"]
];
const WORDS_ZWIT=[
["A1","r","Berg","berg"],["A2","s","Tal","dal"],["B1","r","Gipfel","bergtop"],["A1","r","See","meer"],["A2","e","Seilbahn","kabelbaan"],["A2","e","Wanderung","bergwandeling / hike"],["A2","-","wandern","wandelen (in de bergen)"],["B1","r","Wanderweg","wandelpad"],["B1","e","Hütte","berghut"],["A1","s","Wetter","weer"],["A1","r","Schnee","sneeuw"],["B1","e","Aussicht","uitzicht"],["B1","-","steil","steil"],["B1","-","Ist der Weg schwierig?","is de route moeilijk?"],["A2","-","Wie komme ich zum Bahnhof?","hoe kom ik bij het station?"],["A2","r","Gletscher","gletsjer"],["B1","e","Alp","alpenweide"],["A2","-","klettern","klimmen"],["B1","-","rutschig","glad (onder de voeten)"],["A2","-","bergauf","bergop"],["A2","-","bergab","bergaf"],["B1","e","Höhe","hoogte"],["A2","r","Pass","bergpas"],["B1","-","Wir haben den Gipfel erreicht.","we hebben de top bereikt"],["A2","e","Ausrüstung","uitrusting"],["A2","r","Rucksack","rugzak"],["A2","e","Wasserflasche","waterfles"],["B1","-","Der Weg ist gut markiert.","de route is goed gemarkeerd"],["A2","-","Wie lange dauert die Wanderung?","hoe lang duurt de wandeling?"],["B1","r","Nebel","mist"]
];
const WORDS_GRAM=[
["A2","-","Ich hätte gern einen Kaffee.","ik wil graag een koffie (beleefd bestellen)"],["A2","-","Ich muss morgen arbeiten.","ik moet morgen werken"],["A2","-","Ich kann dir helfen.","ik kan je helpen"],["A2","-","Ich habe gestern gearbeitet.","ik heb gisteren gewerkt"],["B1","-","Ich bin nach Hause gegangen.","ik ben naar huis gegaan"],["A2","-","Morgen gehe ich ins Fitnessstudio.","morgen ga ik naar de sportschool"],["B1","-","Ich weiß, dass es teuer ist.","ik weet dat het duur is"],["B1","-","Ich sehe den Mann.","ik zie de man"],["B1","-","Ich helfe dem Mann.","ik help de man"],["A1","-","Sprechen Sie Deutsch?","spreekt u Duits? (beleefd)"],["A1","-","Kannst du mir helfen?","kun je me helpen? (informeel)"],["B1","-","Ich freue mich auf den Urlaub.","ik verheug me op de vakantie"],["A2","-","Am Wochenende fahre ich nach Bern.","in het weekend rijd ik naar Bern"],["B1","-","Ich glaube, dass er recht hat.","ik denk dat hij gelijk heeft"],["B1","-","Ich rufe dich an, wenn ich Zeit habe.","ik bel je als ik tijd heb"],["B1","-","Der Kunde wartet auf die Antwort.","de klant wacht op het antwoord"],["B1","-","Ich gebe der Frau das Buch.","ik geef de vrouw het boek"],["A2","-","Wir sind ins Kino gegangen.","we zijn naar de bioscoop gegaan"],["A2","-","Hast du das Auto gewaschen?","heb je de auto gewassen?"],["B1","-","Ich darf heute später kommen.","ik mag vandaag later komen"],["B1","-","Wir wollen morgen wandern gehen.","we willen morgen gaan wandelen"],["A1","-","Wie heißen Sie?","hoe heet u? (beleefd)"],["B1","-","Ich weiß nicht, ob er kommt.","ik weet niet of hij komt"],["B1","-","Ich habe ihr geholfen.","ik heb haar geholpen"],["A2","-","Kannst du mir bitte helfen?","kun je me alsjeblieft helpen?"]
];
const WORDS_ZIN=[
["A1","-","Wie spät ist es?","hoe laat is het?"],["A1","-","Wo ist die Toilette?","waar is het toilet?"],["A1","-","Was kostet das?","wat kost dat?"],["A1","-","Ich brauche Hilfe.","ik heb hulp nodig"],["A1","-","Alles klar.","helemaal duidelijk / oké"],["A2","-","Können Sie das wiederholen?","kunt u dat herhalen?"],["A2","-","Ich habe eine Frage.","ik heb een vraag"],["A2","-","Wo kann ich das kaufen?","waar kan ik dat kopen?"],["A2","-","Ich bin neu hier.","ik ben hier nieuw"],["A2","-","Das macht nichts.","dat maakt niet uit"],["B1","-","Könnten Sie mir bitte helfen?","zou u mij alstublieft kunnen helpen?"],["B1","-","Das habe ich nicht verstanden.","dat heb ik niet begrepen"],["B1","-","Wie lange dauert das?","hoe lang duurt dat?"],["B1","-","Ich melde mich später bei dir.","ik neem later contact met je op"],["B1","-","Es kommt darauf an.","het hangt ervan af"],["A1","-","Guten Rutsch!","fijne jaarwisseling!"],["A1","-","Bis bald!","tot snel!"],["A2","-","Ich brauche einen Moment.","ik heb een momentje nodig"],["A2","-","Können Sie langsamer sprechen?","kunt u langzamer spreken?"],["A2","-","Wo ist der Ausgang?","waar is de uitgang?"],["A2","-","Ich habe mich verlaufen.","ik ben verdwaald"],["B1","-","Das ergibt Sinn.","dat is logisch / dat slaat ergens op"],["A2","-","Genau richtig.","precies goed"],["B1","-","Ich bin mir nicht sicher.","ik weet het niet zeker"],["A1","-","Herzlichen Glückwunsch!","gefeliciteerd!"],["A2","-","Gute Besserung!","beterschap!"],["B1","-","Machen Sie sich keine Sorgen.","maakt u zich geen zorgen"],["A1","-","Schönen Tag noch!","nog een fijne dag!"]
];
const CATEGORY_WORDS_DE={bas:WORDS_BAS,tijd:WORDS_TIJD,eten:WORDS_ETEN,fam:WORDS_FAM,verb:WORDS_VERB,reis:WORDS_REIS,sport:WORDS_SPORT,auto:WORDS_AUTO,werk:WORDS_WERK,spreek:WORDS_SPREEK,rest:WORDS_REST,hotel:WORDS_HOTEL,ch:WORDS_CH,zwit:WORDS_ZWIT,gram:WORDS_GRAM,zin:WORDS_ZIN};
const W_DE=Object.entries(CATEGORY_WORDS_DE).flatMap(([cat,list])=>list.map(w=>[cat,...w]));

const ART={r:["der","a-der"],e:["die","a-die"],s:["das","a-das"]};
const GRAM_DE=[
["Werkwoord altijd op plek 2","In een gewone zin staat het vervoegde werkwoord ALTIJD op de tweede plek — ook als de zin met iets anders begint. Begin je met 'morgen', dan komt het werkwoord meteen daarna en schuift 'ik' erachter (inversie).",["Ich gehe morgen ins Gym.|Ik ga morgen naar de gym.","Morgen gehe ich ins Gym.|Morgen ga ik naar de gym.","Am Samstag arbeite ich nicht.|Zaterdag werk ik niet."]],
["Bijzin: werkwoord naar het einde","Na woorden als dass (dat), weil (omdat) en wenn (als) gaat het werkwoord helemaal naar het einde van de bijzin. Dit is dé regel die Duits 'Duits' maakt.",["Ich weiß, dass es teuer ist.|Ik weet dat het duur is.","Ich bleibe zu Hause, weil ich müde bin.|Ik blijf thuis omdat ik moe ben."]],
["Naamvallen light: der → den → dem","Het lidwoord verandert mee met de rol in de zin. Onderwerp: der Mann. Lijdend voorwerp (accusatief): den Mann. Na o.a. helfen, mit, zu (datief): dem Mann. Die en das veranderen alleen in de datief (der/dem).",["Der Mann ist nett.|De man is aardig. (onderwerp)","Ich sehe den Mann.|Ik zie de man. (accusatief)","Ich helfe dem Mann.|Ik help de man. (datief)"]],
["Verleden tijd: het Perfekt","Spreektaal gebruikt bijna altijd het Perfekt: haben/sein + voltooid deelwoord achteraan. Sein bij beweging of verandering (gegangen, gefahren), haben bij de rest. Net als in het Nederlands, alleen strikter: het deelwoord staat écht op het einde.",["Ich habe gestern gearbeitet.|Ik heb gisteren gewerkt.","Ich bin nach Zürich gefahren.|Ik ben naar Zürich gereden."]],
["Modale werkwoorden","Müssen (moeten), können (kunnen), wollen (willen), dürfen (mogen): het modale werkwoord staat op plek 2, het hele werkwoord gaat naar het einde.",["Ich muss morgen arbeiten.|Ik moet morgen werken.","Kann ich mit Karte zahlen?|Kan ik pinnen?","Ich will Deutsch lernen.|Ik wil Duits leren."]],
["Du of Sie? (+ Zwitserse tip)","Sie (met hoofdletter) tegen onbekenden, personeel en klanten — beleefd en altijd veilig. Du tegen vrienden en in de gym. In Zwitserland werkt je standaard Duits overal; je hoort er alleen Grüezi in plaats van Guten Tag en merci in plaats van danke. Gewoon Hochdeutsch terugpraten is prima.",["Sprechen Sie Englisch?|Spreekt u Engels?","Kannst du mir helfen?|Kun je me helpen?"]]
];

/* ================= TURKS ================= */
const CATS_TR={...CATS_DE,ch:"Typisch Turks"};
const CAT_ICON_TR={...CAT_ICON_DE,eten:"🥙",rest:"🍲",zwit:"🎈",ch:"🍵"};

const WORDS_TR_BAS=[
["A1","-","Günaydın","goedemorgen"],["A1","-","İyi günler","goedendag"],["A1","-","İyi akşamlar","goedenavond"],["A1","-","Hoşça kal","doei (tegen wie vertrekt)"],["A1","-","Güle güle","doei (tegen wie blijft)"],["A1","-","lütfen","alsjeblieft"],["A1","-","teşekkür ederim","dank je wel"],["A1","-","teşekkürler","bedankt"],["A1","-","affedersiniz","sorry / pardon"],["A1","-","Nasılsın?","hoe gaat het? (informeel)"],["A1","-","iyi","goed"],["A1","-","kötü","slecht"],["A1","-","Benim adım …","ik heet …"],["A1","-","Anlamıyorum","ik begrijp het niet"],["A1","-","yavaş","langzaam"],["A1","-","tabii","natuurlijk"],["A1","-","belki","misschien"],["A1","-","Merhaba","hallo"],["A1","-","Evet","ja"],["A1","-","Hayır","nee"],["A1","-","Hoşgeldiniz","welkom","Als antwoord zeg je 'Hoşbulduk' — de twee groeten horen bij elkaar."],["A1","-","Hoşbulduk","dankjewel voor het welkom (antwoord op Hoşgeldiniz)"],["A2","-","Nasılsınız?","hoe gaat het? (beleefd, meervoud)"],["A2","-","Efendim?","pardon? (niet verstaan)"],["A2","-","İyi şanslar","veel geluk"],["A2","-","Rica ederim","graag gedaan"],["A2","-","Hollanda'dan geliyorum","ik kom uit Nederland"],["A2","-","Görüşürüz","tot ziens (zie je snel)"],["B1","-","Memnun oldum","aangenaam kennis te maken"],["B1","-","Önemli değil","het geeft niet"],["B1","-","Kolay gelsin","gezegd tegen iemand die werkt, letterlijk 'moge het makkelijk komen'"]
];
const WORDS_TR_TIJD=[
["A1","-","bir","één"],["A1","-","iki","twee"],["A1","-","üç","drie"],["A1","-","dört","vier"],["A1","-","beş","vijf"],["A1","-","altı","zes"],["A1","-","yedi","zeven"],["A1","-","sekiz","acht"],["A1","-","dokuz","negen"],["A1","-","on","tien"],["A1","-","yirmi","twintig"],["A1","-","yüz","honderd"],["A1","-","bugün","vandaag"],["A1","-","yarın","morgen"],["A1","-","dün","gisteren"],["A1","-","şimdi","nu"],["A1","-","sonra","later"],["A1","-","saat","uur"],["A1","-","hafta","week"],["A1","-","yıl","jaar"],["A1","-","on bir","elf"],["A1","-","on iki","twaalf"],["A1","-","otuz","dertig"],["A1","-","Pazartesi","maandag"],["A1","-","Cuma","vrijdag"],["A2","-","ay","maand"],["A2","-","her zaman","altijd"],["A2","-","bazen","soms"],["B1","-","yakında","binnenkort"]
];
const WORDS_TR_ETEN=[
["A1","-","su","water"],["A1","-","kahve","koffie"],["A1","-","çay","thee"],["A1","-","ekmek","brood"],["A1","-","peynir","kaas"],["A2","-","kahvaltı","ontbijt"],["A2","-","öğle yemeği","lunch"],["A2","-","akşam yemeği","avondeten"],["A1","-","elma","appel"],["A1","-","et","vlees"],["A2","-","tavuk","kip (gerecht)"],["A1","-","balık","vis"],["A2","-","sebze","groente"],["A2","-","meyve","fruit"],["A2","-","hesap","rekening"],["A2","-","sipariş vermek","bestellen"],["A1","-","lezzetli","lekker"],["A2","-","tok","vol (verzadigd)"],["A1","-","restoran","restaurant"],["A2","-","menü","menukaart"],["A2","-","bira","bier"],["A2","-","şarap","wijn"],["A2","-","çorba","soep"],["A2","-","salata","salade"],["A2","-","süt","melk"],["A2","-","yumurta","ei"],["B1","-","baharatlı","pittig / kruidig"],["B1","-","vejetaryen","vegetarisch"]
];
const WORDS_TR_FAM=[
["A1","-","aile","familie / gezin"],["A1","-","baba","vader"],["A1","-","anne","moeder"],["A1","-","kardeş","broer of zus","Kardeş is geslachtsneutraal. Specifiek: erkek kardeş = broer, kız kardeş = zus."],["A2","-","abi","oudere broer","Voor een OUDERE broer zeg je 'abi', voor jongere gewoon 'kardeş' — leeftijd bepaalt het woord, niet alleen geslacht."],["A2","-","abla","oudere zus"],["A1","-","oğul","zoon"],["A1","-","kız","dochter","Kız betekent ook gewoon 'meisje' — context bepaalt de betekenis."],["A1","-","arkadaş","vriend(in)"],["A2","-","erkek arkadaş","vriendje"],["A2","-","kız arkadaş","vriendinnetje"],["A2","-","koca","echtgenoot"],["B1","-","eş","echtgenoot / echtgenote (neutraal)"],["A1","-","çocuk","kind"],["B1","-","ebeveyn","ouders"],["A1","-","dede","opa"],["A1","-","büyükanne","oma"],["A2","-","evli","getrouwd"],["A2","-","komşu","buurman / buurvrouw"],["A1","-","insanlar","mensen"],["A1","-","genç","jong"],["A1","-","yaşlı","oud"],["A2","-","amca","oom (vaderskant)","Turks maakt onderscheid: amca = vaders broer, dayı = moeders broer."],["A2","-","dayı","oom (moederskant)"],["A2","-","teyze","tante (moederskant)"],["A2","-","hala","tante (vaderskant)"],["B1","-","boşanmış","gescheiden"],["B1","-","torun","kleinkind"],["B1","-","akraba","verwant"]
];
const WORDS_TR_VERB=[
["A1","-","olmak","zijn"],["A1","-","var / yok","hebben (er is / er is niet)","Turks heeft geen werkwoord voor bezit: 'Param var' = 'ik heb geld' (letterlijk: mijn geld is-er)."],["A1","-","gitmek","gaan"],["A1","-","gelmek","komen"],["A1","-","yapmak","doen / maken"],["A1","-","söylemek","zeggen"],["A1","-","görmek","zien"],["A1","-","duymak","horen"],["A1","-","konuşmak","spreken"],["A1","-","yemek","eten"],["A1","-","içmek","drinken"],["A1","-","almak","kopen / nemen","Almak betekent zowel 'kopen' als 'nemen' — de context maakt het duidelijk."],["A2","-","ihtiyacı olmak","nodig hebben"],["A1","-","bilmek","weten"],["A2","-","düşünmek","denken"],["A2","-","bulmak","vinden"],["A2","-","yardım etmek","helpen"],["A2","-","aramak","zoeken / bellen","Aramak betekent ook 'bellen (telefoneren)' — heel gangbaar dubbelgebruik."],["A1","-","vermek","geven"],["A2","-","çalışmak","werken"],["A2","-","oynamak","spelen"],["A2","-","okumak","lezen"],["A2","-","yazmak","schrijven"],["B1","-","izin vermek","toestaan"],["B1","-","kaçınmak","vermijden"],["B1","-","acele etmek","zich haasten"]
];
const WORDS_TR_REIS=[
["A2","-","istasyon","station"],["A2","-","tren","trein"],["A2","-","uçak","vliegtuig"],["A2","-","havalimanı","luchthaven"],["A2","-","bilet","kaartje / ticket"],["A1","-","sol","links"],["A1","-","sağ","rechts"],["A2","-","düz","rechtdoor"],["A1","-","sokak","straat"],["A1","-","şehir","stad"],["A1","-","otel","hotel"],["A1","-","oda","kamer"],["A2","-","anahtar","sleutel"],["A2","-","seyahat","reis"],["A2","-","tatil","vakantie"],["A2","-","bagaj","bagage"],["A2","-","kalkmak","vertrekken"],["A2","-","varmak","aankomen"],["A2","-","rezervasyon yapmak","boeken"],["B1","-","gezi","uitje / excursie"],["A2","-","valiz","koffer"],["A2","-","gecikme","vertraging"],["A2","-","kimlik","identiteitsbewijs"],["B1","-","aktarma","aansluiting (overstap)"],["B1","-","aktarma yapmak","overstappen"],["B1","-","sınır","grens"]
];
const WORDS_TR_SPORT=[
["A2","-","spor","sport"],["A2","-","antrenman yapmak","trainen"],["A1","-","koşmak","hardlopen"],["A2","-","yüzmek","zwemmen"],["B1","-","kas","spier"],["A2","-","güçlü","sterk"],["A1","-","yorgun","moe"],["A2","-","sağlıklı","gezond"],["A1","-","hasta","ziek"],["A2","-","vücut","lichaam"],["A2","-","kalp","hart"],["B1","-","nefes almak","ademen"],["B1","-","dinlenmek","uitrusten"],["A2","-","uyku","slaap"],["A1","-","uyumak","slapen"],["A2","-","hedef","doel"],["A1","-","hızlı","snel"],["B1","-","güç","kracht"],["A2","-","pratik yapmak","oefenen"],["B1","-","kilo","gewicht"],["A2","-","yürüyüş yapmak","wandelen (rustig)"],["A2","-","formda","fit"],["B1","-","yaralanmak","zich blesseren"],["B1","-","yaralanma","blessure"],["B1","-","iyileşmek","herstellen"]
];
const WORDS_TR_AUTO=[
["A1","-","araba","auto"],["A2","-","araç","voertuig"],["A2","-","lastik","band"],["A2","-","tekerlek","wiel"],["A2","-","motor","motor"],["B1","-","motor kaputu","motorkap"],["A2","-","bagaj","kofferbak"],["B1","-","ön cam","voorruit"],["B1","-","boya","lak"],["B1","-","jant","velg"],["A2","-","deri","leer"],["B1","-","çizik","kras"],["B1","-","cilalamak","polijsten"],["A2","-","temizlemek","reinigen"],["A1","-","yıkamak","wassen"],["B1","-","köpük","schuim"],["B1","-","bez","doek"],["B1","-","elektrikli süpürge","stofzuiger"],["B1","-","parlamak","glanzen"],["A2","-","tamirhane","werkplaats / garage"],["A2","-","benzin almak","tanken"],["A2","-","sürücü","bestuurder"],["A2","-","fren","rem"],["B1","-","emniyet kemeri","veiligheidsgordel"],["B1","-","tamir etmek","repareren"],["B1","-","yağ değişimi","olieverversing"]
];
const WORDS_TR_WERK=[
["A1","-","iş","werk"],["A2","-","müşteri","klant"],["A2","-","randevu","afspraak"],["A2","-","şirket","bedrijf"],["A2","-","fiyat","prijs"],["A1","-","para","geld"],["A1","-","pahalı","duur"],["A2","-","ucuz","goedkoop"],["B1","-","sözleşme","contract"],["B1","-","sigorta","verzekering"],["B1","-","vergi","belasting"],["B1","-","serbest çalışan","zelfstandig (zzp)"],["B1","-","teklif","offerte / aanbod"],["A2","-","kazanmak","verdienen"],["A2","-","ödemek","betalen"],["A2","-","dakik","stipt / op tijd"],["B1","-","mesai","werktijd / overwerk"],["B1","-","deneyim","ervaring"],["B1","-","güvenilir","betrouwbaar"],["A2","-","patron","baas"],["A2","-","meslektaş","collega"],["B1","-","istifa","ontslag"],["B1","-","pazarlık yapmak","onderhandelen"],["A2","-","maaş","salaris"],["B1","-","zam","loonsverhoging"],["B1","-","evden çalışmak","vanuit huis werken"]
];
const WORDS_TR_SPREEK=[
["B1","-","fikir","mening"],["B1","-","Bence …","volgens mij / ik vind dat …","'Bence' = ben (ik) + -ce: een mooi voorbeeld van agglutinatie, één achtervoegsel maakt er 'volgens mij' van."],["B1","-","katılıyorum","ik ben het eens"],["B1","-","katılmıyorum","ik ben het niet eens"],["A2","-","öneri","voorstel"],["A2","-","soru","vraag"],["A2","-","cevap","antwoord"],["B1","-","açıklamak","uitleggen"],["A2","-","anlamak","begrijpen"],["B1","-","tavsiye etmek","aanbevelen"],["B1","-","aslında","eigenlijk"],["B1","-","muhtemelen","waarschijnlijk"],["A2","-","önemli","belangrijk"],["B1","-","karar","beslissing"],["B1","-","karar vermek","beslissen"],["B1","-","dört gözle beklemek","zich verheugen op","Letterlijk 'met vier ogen wachten' — een levendige uitdrukking voor ergens naar uitkijken."],["A2","-","Özür dilerim","het spijt me"],["A1","-","sorun değil","geen probleem"],["B1","-","sebep","reden"],["B1","-","bu yüzden","daarom"],["A2","-","doğru","juist / klopt"],["A2","-","yanlış","fout / onjuist"],["B1","-","haklısın","je hebt gelijk"],["B1","-","belki de","misschien wel"],["B1","-","abartmak","overdrijven"]
];
const WORDS_TR_REST=[
["A2","-","İki kişilik bir masa, lütfen.","een tafel voor twee, graag"],["A2","-","Menüyü alabilir miyim?","mag ik de menukaart?"],["A2","-","Bir su rica ediyorum.","ik wil graag een water"],["A2","-","Ne tavsiye edersiniz?","wat beveelt u aan?"],["A2","-","Hesabı alabilir miyim?","mag ik de rekening?"],["B1","-","Ayrı ödeyebilir miyiz?","kunnen we apart betalen?"],["A2","-","Kartla ödeyebilir miyim?","kan ik met kaart betalen?"],["A1","-","Afiyet olsun!","eet smakelijk"],["B1","-","Elimize sağlık!","complimenten voor de kok","Letterlijk 'gezondheid voor onze handen' — een warme Turkse manier om een maaltijd te prijzen."],["A2","-","Çok lezzetliydi.","het was erg lekker"],["A2","-","Başka bir şey?","nog iets?"],["B1","-","Fıstık alerjim var.","ik ben allergisch voor noten"],["A2","-","Soğansız, lütfen.","zonder ui, graag"],["A2","-","musluk suyu","kraanwater"],["A2","-","garson","ober / serveerder"],["A2","-","tatlı","toetje / dessert"],["A2","-","ön yemek","voorgerecht"],["A2","-","ana yemek","hoofdgerecht"],["A2","-","Masa boş mu?","is deze tafel vrij?"],["A1","-","Şerefe!","proost!"],["A2","-","bahşiş","fooi"],["B1","-","Acı mı?","is het pittig?"],["A2","-","Doydum.","ik zit vol"],["A2","-","Rezervasyonum var.","ik heb een reservering"],["A2","-","Kaç kişisiniz?","voor hoeveel personen?"]
];
const WORDS_TR_HOTEL=[
["A2","-","Bir oda ayırttım.","ik heb een kamer gereserveerd"],["A2","-","tek kişilik oda","eenpersoonskamer"],["A2","-","İki gece için çift kişilik oda.","tweepersoonskamer voor twee nachten"],["A2","-","Kahvaltı dahil mi?","is het ontbijt inbegrepen?"],["A2","-","Kahvaltı saat kaçta?","hoe laat is het ontbijt?"],["A2","-","Çıkış saati kaçta?","tot hoe laat is het uitchecken?"],["A2","-","Wifi şifresi nedir?","wat is het wifi-wachtwoord?"],["A2","-","Otopark var mı?","is er een parkeerplaats?"],["B1","-","Oda çok gürültülü.","de kamer is te lawaaiig"],["B1","-","Kalorifer çalışmıyor.","de verwarming doet het niet"],["B1","-","Bagajımı burada bırakabilir miyim?","kan ik mijn bagage hier laten?"],["A2","-","Taksi çağırabilir misiniz?","kunt u een taxi bellen?"],["A2","-","resepsiyon","receptie"],["A2","-","asansör","lift"],["A2","-","Boş odanız var mı?","heeft u nog kamers vrij?"],["A2","-","minibar","minibar"],["A2","-","havlu","handdoek"],["B1","-","Beni yedide uyandırabilir misiniz?","kunt u me om zeven uur wekken?"],["A2","-","oda servisi","roomservice"],["A2","-","Nerede park edebilirim?","waar kan ik parkeren?"],["A2","-","nevresim","beddengoed"],["A2","-","Check-out yapmak istiyorum.","ik wil graag uitchecken"],["A2","-","anahtar kartı","sleutelkaart"],["B1","-","Başka bir oda verebilir misiniz?","kunt u ons een andere kamer geven?"],["A2","-","Oda hâlâ boş mu?","is de kamer nog vrij?"]
];
const WORDS_TR_CH=[
["A2","-","Çok yaşa!","gezondheid! (tegen iemand die niest)","Het gebruikelijke antwoord is 'Sen de gör' (jij ook!)."],["A2","-","Sen de gör","jij ook! (antwoord op Çok yaşa)"],["B1","-","Nazar değmesin","moge het geen boze blik krijgen","Gezegd bij iets moois, verwijst naar het bijgeloof rond de nazar boncuğu (blauwe kraal)."],["B1","-","Maşallah","prachtig! / God behoede","Compliment-uitdrukking die tegelijk het boze oog afweert."],["B1","-","İnşallah","als God het wil / hopelijk"],["A2","-","Buyurun","alstublieft / ga uw gang (bij iets aanbieden)"],["A2","-","Eyvallah","bedankt / oké (informeel)"],["A2","-","Çay ister misiniz?","wilt u thee?"],["A1","-","Bir çay daha","nog een thee"],["A2","-","Türk kahvesi","Turkse koffie"],["A2","-","simit","sesamring (Turks straatgebak)"],["B1","-","Kapalıçarşı","de Grote Bazaar (Istanbul)"],["A2","-","hamam","Turks bad"],["B1","-","nazar boncuğu","blauwe kraal tegen het boze oog"],["A2","-","Geçmiş olsun","beterschap (bij ziekte of pech)"],["B1","-","Hayırlı olsun","moge het goed uitpakken (bij een nieuwe start)"],["B1","-","Allah'a emanet ol","het ga je goed (afscheidsgroet)"],["B1","-","Ellerine sağlık","complimenten voor je (hand)werk"],["A2","-","bayram","feestdag"],["A2","-","Bayramınız kutlu olsun","fijne feestdag!"],["A2","-","dolmuş","gedeelde minibustaxi"],["B1","-","Türk usulü","op zijn Turks / de Turkse manier"],["B1","-","keyif","genot / plezier"],["A1","-","sıcak","warm","Sıcak betekent ook 'gastvrij, hartelijk' als je het over mensen hebt."]
];
const WORDS_TR_ZWIT=[
["A1","-","dağ","berg"],["A2","-","vadi","dal"],["B1","-","zirve","bergtop"],["A1","-","göl","meer"],["A2","-","teleferik","kabelbaan"],["A2","-","yürüyüş","wandeling / hike"],["A2","-","yürüyüş yolu","wandelpad"],["B1","-","dağ evi","berghut"],["A1","-","hava durumu","weer"],["A1","-","kar","sneeuw"],["B1","-","manzara","uitzicht"],["B1","-","dik","steil"],["B1","-","Yol zor mu?","is de route moeilijk?"],["A2","-","İstasyona nasıl giderim?","hoe kom ik bij het station?"],["A2","-","buzul","gletsjer"],["B1","-","yayla","alpenweide / hoogvlakte"],["A2","-","tırmanmak","klimmen"],["B1","-","kaygan","glad (onder de voeten)"],["A2","-","sıcak hava balonu","heteluchtballon","Cappadocië is wereldberoemd om de heteluchtballonvaarten bij zonsopgang."],["B1","-","peri bacaları","sprookjesschoorstenen","De unieke rotsformaties van Cappadocië, ontstaan door erosie."],["B1","-","vadi turu","dalentocht"],["B1","-","Zirveye ulaştık.","we hebben de top bereikt"],["A2","-","ekipman","uitrusting"],["A2","-","sırt çantası","rugzak"],["A2","-","su şişesi","waterfles"],["A2","-","Yürüyüş ne kadar sürer?","hoe lang duurt de wandeling?"],["B1","-","sis","mist"]
];
const WORDS_TR_GRAM=[
["A2","-","Kitabı okuyorum.","ik lees het boek","-yor is de uitgang voor de tegenwoordige tijd: oku+yor+um = 'ik ben aan het lezen'."],["A2","-","Yarın İstanbul'a gidiyorum.","morgen ga ik naar Istanbul","Richting wordt uitgedrukt met de uitgang -a/-e, niet met een los voorzetsel 'naar'."],["A2","-","Evde kalıyorum çünkü yorgunum.","ik blijf thuis omdat ik moe ben"],["A2","-","Dün çalıştım.","ik heb gisteren gewerkt","Verleden tijd -tı/-ti/-tu/-tü past zich aan op klank: dit heet klinkerharmonie."],["B1","-","Eve gittim.","ik ben naar huis gegaan"],["A2","-","Yarın spor salonuna gidiyorum.","morgen ga ik naar de sportschool"],["B1","-","Pahalı olduğunu biliyorum.","ik weet dat het duur is","Turks gebruikt geen los voegwoord 'dat': de bijzin wordt een zelfstandig naamwoord met -dığı(nı)."],["B1","-","Adamı görüyorum.","ik zie de man","Accusatief -ı bij een bepaald lijdend voorwerp (belirtme hali)."],["B1","-","Adama yardım ediyorum.","ik help de man","Datief -a: 'yardım etmek' (helpen) vraagt om de datiefvorm."],["A1","-","Türkçe biliyor musunuz?","spreekt u Turks? (beleefd)"],["A1","-","Bana yardım edebilir misin?","kun je me helpen? (informeel)"],["B1","-","Tatili iple çekiyorum.","ik verheug me op de vakantie","Idioom: 'iple çekmek' = ergens vol verlangen naar uitkijken."],["B1","-","Yarın gelip gelmeyeceğini bilmiyorum.","ik weet niet of hij morgen komt"],["B1","-","Ona yardım ettim.","ik heb hem/haar geholpen"],["A2","-","Bana yardım eder misin?","kun je me alsjeblieft helpen?"],["A2","-","Kahve içmek istiyorum.","ik wil graag koffie drinken"],["B1","-","Yarın çalışmam lazım.","ik moet morgen werken","'Lazım' (nodig/moeten) + bezittelijke uitgang op het werkwoord: çalışma+m lazım."],["A2","-","Sana yardım edebilirim.","ik kan je helpen"],["A1","-","evler","huizen","Meervoud -ler/-lar volgt klinkerharmonie: evler, maar kitaplar."],["A1","-","kitaplar","boeken"],["A2","-","Kalemim var.","ik heb een pen","Bezit wordt uitgedrukt met 'var' (er is), niet met een werkwoord 'hebben'."],["A2","-","Param yok.","ik heb geen geld","'Yok' is het tegenovergestelde van 'var': 'er is niet'."]
];
const WORDS_TR_ZIN=[
["A1","-","Saat kaç?","hoe laat is het?"],["A1","-","Tuvalet nerede?","waar is het toilet?"],["A1","-","Bu ne kadar?","wat kost dat?"],["A1","-","Yardıma ihtiyacım var.","ik heb hulp nodig"],["A2","-","Anlaşıldı.","helemaal duidelijk / oké"],["A2","-","Tekrar edebilir misiniz?","kunt u dat herhalen?"],["A2","-","Bir sorum var.","ik heb een vraag"],["A2","-","Bunu nereden alabilirim?","waar kan ik dat kopen?"],["A2","-","Buraya yeniyim.","ik ben hier nieuw"],["A2","-","Önemli değil.","dat maakt niet uit"],["B1","-","Bana yardım edebilir misiniz?","zou u mij kunnen helpen?"],["B1","-","Anlamadım.","dat heb ik niet begrepen"],["B1","-","Ne kadar sürer?","hoe lang duurt dat?"],["B1","-","Sana sonra haber veririm.","ik neem later contact met je op"],["B1","-","Duruma göre değişir.","het hangt ervan af"],["A1","-","İyi yıllar!","fijne jaarwisseling!"],["A1","-","Görüşmek üzere!","tot snel!"],["A2","-","Bir dakika lütfen.","een momentje alstublieft"],["A2","-","Daha yavaş konuşabilir misiniz?","kunt u langzamer spreken?"],["A2","-","Çıkış nerede?","waar is de uitgang?"],["A2","-","Kayboldum.","ik ben verdwaald"],["B1","-","Mantıklı.","dat is logisch"],["A2","-","Tam olarak öyle.","precies goed"],["B1","-","Emin değilim.","ik weet het niet zeker"],["A1","-","Tebrikler!","gefeliciteerd!"],["A2","-","Geçmiş olsun!","beterschap!"],["B1","-","Merak etme.","maak je geen zorgen"],["A1","-","İyi günler dilerim!","nog een fijne dag!"]
];
const CATEGORY_WORDS_TR={bas:WORDS_TR_BAS,tijd:WORDS_TR_TIJD,eten:WORDS_TR_ETEN,fam:WORDS_TR_FAM,verb:WORDS_TR_VERB,reis:WORDS_TR_REIS,sport:WORDS_TR_SPORT,auto:WORDS_TR_AUTO,werk:WORDS_TR_WERK,spreek:WORDS_TR_SPREEK,rest:WORDS_TR_REST,hotel:WORDS_TR_HOTEL,ch:WORDS_TR_CH,zwit:WORDS_TR_ZWIT,gram:WORDS_TR_GRAM,zin:WORDS_TR_ZIN};
const W_TR=Object.entries(CATEGORY_WORDS_TR).flatMap(([cat,list])=>list.map(w=>[cat,...w]));

/* ================= taal-config & decks ================= */
const DECKS={de:W_DE,tr:W_TR};
const LANGS={
  de:{id:"de",name:"Duits",flag:"🇩🇪",speechLang:"de-DE",hasArticles:true,cats:CATS_DE,catIcon:CAT_ICON_DE,gramGuide:GRAM_DE},
  tr:{id:"tr",name:"Turks",flag:"🇹🇷",speechLang:"tr-TR",hasArticles:false,cats:CATS_TR,catIcon:CAT_ICON_TR}
};
